"""refactor student and teacher models

Revision ID: def89e456595
Revises: 3d3d03b53449
Create Date: 2024-06-23 12:15:41.879811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "def89e456595"
down_revision: Union[str, None] = "3d3d03b53449"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_teacher_lastname_firstname_patronymic"),
        "teacher",
        ["lastname", "firstname", "patronymic"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_teacher_lastname_firstname_patronymic"),
        "teacher",
        type_="unique",
    )
    # ### end Alembic commands ###
