"""empty message

Revision ID: 5462af96779c
Revises: 69f6b4b5e49a
Create Date: 2024-06-23 20:30:47.049497

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5462af96779c"
down_revision: Union[str, None] = "69f6b4b5e49a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_teacher_lastname_firstname_patronymic", "teacher", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_teacher_lastname_firstname_patronymic"),
        "teacher",
        ["lastname", "firstname", "patronymic"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_teacher_lastname_firstname_patronymic"),
        "teacher",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_teacher_lastname_firstname_patronymic",
        "teacher",
        ["lastname", "firstname", "patronymic"],
    )
    # ### end Alembic commands ###
