"""Add unique constraint for semester

Revision ID: 6d0454cbc2c0
Revises: 5462af96779c
Create Date: 2024-06-24 15:39:13.876563

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d0454cbc2c0"
down_revision: Union[str, None] = "5462af96779c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_schedule",
        sa.Column("weekly_schedule_id", sa.Integer(), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_daily_schedule_weekly_schedule_id_weekly_schedule"),
        "daily_schedule",
        "weekly_schedule",
        ["weekly_schedule_id"],
        ["id"],
    )
    op.create_unique_constraint(
        op.f("uq_semester_year_number"), "semester", ["year", "number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_semester_year_number"), "semester", type_="unique"
    )
    op.drop_constraint(
        op.f("fk_daily_schedule_weekly_schedule_id_weekly_schedule"),
        "daily_schedule",
        type_="foreignkey",
    )
    op.drop_column("daily_schedule", "weekly_schedule_id")
    # ### end Alembic commands ###
