"""empty message

Revision ID: d73629aa45e6
Revises: def89e456595
Create Date: 2024-06-23 12:37:41.006393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d73629aa45e6"
down_revision: Union[str, None] = "def89e456595"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "group", sa.Column("curator_id", sa.Integer(), nullable=False)
    )
    op.drop_constraint("uq_group_curator", "group", type_="unique")
    op.create_unique_constraint(
        op.f("uq_group_curator_id"), "group", ["curator_id"]
    )
    op.drop_constraint("fk_group_curator_teacher", "group", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_group_curator_id_teacher"),
        "group",
        "teacher",
        ["curator_id"],
        ["id"],
    )
    op.drop_column("group", "curator")
    op.drop_constraint(
        "uq_teacher_lastname_firstname_patronymic", "teacher", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_teacher_lastname_firstname_patronymic"),
        "teacher",
        ["lastname", "firstname", "patronymic"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_teacher_lastname_firstname_patronymic"),
        "teacher",
        type_="unique",
    )
    op.create_unique_constraint(
        "uq_teacher_lastname_firstname_patronymic",
        "teacher",
        ["lastname", "firstname", "patronymic"],
    )
    op.add_column(
        "group",
        sa.Column(
            "curator", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_constraint(
        op.f("fk_group_curator_id_teacher"), "group", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_group_curator_teacher", "group", "teacher", ["curator"], ["id"]
    )
    op.drop_constraint(op.f("uq_group_curator_id"), "group", type_="unique")
    op.create_unique_constraint("uq_group_curator", "group", ["curator"])
    op.drop_column("group", "curator_id")
    # ### end Alembic commands ###
